name: AppScan CodeSweep
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  AppScanCodeSweep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run AppScan CodeSweep
        uses: HCL-Technologies/codesweep-action@v1
        with:
          status: 'success'
